/*
 * Java Course Movie App API
 * Sample Movie App AI
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package pl.wsb.students.api.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

/**
 * ActorRatings
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2020-04-30T07:31:54.867Z")
public class ActorRatings   {
  @JsonProperty("movie")
  private Movie movie = null;

  @JsonProperty("rate")
  private Integer rate = null;

  public ActorRatings movie(Movie movie) {
    this.movie = movie;
    return this;
  }

  /**
   * Get movie
   * @return movie
   **/
  @JsonProperty("movie")
  @ApiModelProperty(value = "")
  public Movie getMovie() {
    return movie;
  }

  public void setMovie(Movie movie) {
    this.movie = movie;
  }

  public ActorRatings rate(Integer rate) {
    this.rate = rate;
    return this;
  }

  /**
   * Rate in movie
   * @return rate
   **/
  @JsonProperty("rate")
  @ApiModelProperty(value = "Rate in movie")
  public Integer getRate() {
    return rate;
  }

  public void setRate(Integer rate) {
    this.rate = rate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActorRatings actorRatings = (ActorRatings) o;
    return Objects.equals(this.movie, actorRatings.movie) &&
        Objects.equals(this.rate, actorRatings.rate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(movie, rate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActorRatings {\n");
    
    sb.append("    movie: ").append(toIndentedString(movie)).append("\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

